DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
  code          VARCHAR(100) NOT NULL,
  name          VARCHAR(100) DEFAULT NULL,
  address       VARCHAR(100) DEFAULT NULL,
  phoneNo1      VARCHAR(100) DEFAULT NULL,
  phoneNo2      VARCHAR(100) DEFAULT NULL,
  creditLimit   DECIMAL(12, 2) DEFAULT 0.00,
  currentCredit DECIMAL(12, 2) DEFAULT 0.00,
  PRIMARY KEY (code));

DROP TABLE IF EXISTS ORDER_LIST;
CREATE TABLE ORDER_LIST (
  id         INT NOT NULL AUTO_INCREMENT,

  quantity   INT DEFAULT 0,
  unitPrice  DECIMAL(12, 2) DEFAULT 0.0,
  totalPrice DECIMAL(12, 2) DEFAULT 0.0,
  PRIMARY KEY (id));

DROP TABLE IF EXISTS SALES_ORDER;
CREATE TABLE SALES_ORDER (
  orderNumber  VARCHAR(100) NOT NULL,
  customerCode VARCHAR(100) NOT NULL,
  totalPrice   DECIMAL(12, 2) DEFAULT 0.0,
  PRIMARY KEY (orderNumber));

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
  code        VARCHAR(100) NOT NULL,
  description VARCHAR(100) NOT NULL,
  price       DECIMAL(12, 2) DEFAULT 0.0,
  quantity    INT DEFAULT 0,
  PRIMARY KEY (code));